apiVersion: v1  #para persistir sqlite
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
  namespace: desenvolvimento
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi