// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserMicroservice.Infra.Data;

#nullable disable

namespace UserMicroservice.Infra.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20251229001645_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("UserMicroservice.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAccess")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("248a2ef7-eda1-4a60-987a-32a228a0cdcb"),
                            LastAccess = new DateTime(2025, 12, 29, 0, 16, 45, 160, DateTimeKind.Utc).AddTicks(216),
                            Role = "Administrador",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("f3dbde56-d8c0-427a-8a54-a22d08577cda"),
                            LastAccess = new DateTime(2025, 12, 29, 0, 16, 45, 160, DateTimeKind.Utc).AddTicks(219),
                            Role = "Usuario",
                            Username = "usuarioGamer"
                        });
                });

            modelBuilder.Entity("UserMicroservice.Domain.Entities.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8bf467b1-61f2-4c5d-828a-b9f1140c0b3d"),
                            Description = "Pode gerenciar usuários",
                            Name = "Administrador",
                            UserId = new Guid("248a2ef7-eda1-4a60-987a-32a228a0cdcb")
                        },
                        new
                        {
                            Id = new Guid("40a3f868-b6b8-4980-857f-486d407997f6"),
                            Description = "Pode visualizar relatórios",
                            Name = "Usuario",
                            UserId = new Guid("248a2ef7-eda1-4a60-987a-32a228a0cdcb")
                        });
                });

            modelBuilder.Entity("UserMicroservice.Domain.Entities.User", b =>
                {
                    b.OwnsOne("UserMicroservice.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.HasData(
                                new
                                {
                                    UserId = new Guid("248a2ef7-eda1-4a60-987a-32a228a0cdcb"),
                                    Address = "admin@system.com"
                                },
                                new
                                {
                                    UserId = new Guid("f3dbde56-d8c0-427a-8a54-a22d08577cda"),
                                    Address = "gamer@system.com"
                                });
                        });

                    b.OwnsOne("UserMicroservice.Domain.ValueObjects.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.HasData(
                                new
                                {
                                    UserId = new Guid("248a2ef7-eda1-4a60-987a-32a228a0cdcb"),
                                    Value = "Admin@123"
                                },
                                new
                                {
                                    UserId = new Guid("f3dbde56-d8c0-427a-8a54-a22d08577cda"),
                                    Value = "gamer@123"
                                });
                        });

                    b.Navigation("Email");

                    b.Navigation("Password")
                        .IsRequired();
                });

            modelBuilder.Entity("UserMicroservice.Domain.Entities.UserPermission", b =>
                {
                    b.HasOne("UserMicroservice.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
